// <auto-generated />
using System;
using ApiJBA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiJBA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260609181632_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiJBA.Entidades.Alumno", b =>
                {
                    b.Property<string>("ci_alumno")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("cardiovascular")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ci_representante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("edad_alumno")
                        .HasColumnType("int");

                    b.Property<int>("estado_alumno")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_registro_a")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_salida_a")
                        .HasColumnType("datetime2");

                    b.Property<string>("foto_a")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("motivo_a")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nombre_alumno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("partida_nacimiento")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ci_alumno");

                    b.HasIndex("ci_representante");

                    b.ToTable("alumnos");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Asistencia", b =>
                {
                    b.Property<int>("id_dia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_dia"));

                    b.Property<string>("ci_p")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("entrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("salida")
                        .HasColumnType("datetime2");

                    b.HasKey("id_dia");

                    b.HasIndex("ci_p");

                    b.ToTable("asistencias");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Categoria", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_categoria"));

                    b.Property<string>("nombre_categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id_categoria");

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Colaboracion", b =>
                {
                    b.Property<int>("id_orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_orden"));

                    b.Property<string>("ci_p")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ci_representante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_proveedor")
                        .HasColumnType("int");

                    b.Property<string>("observacion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id_orden");

                    b.HasIndex("ci_p");

                    b.HasIndex("ci_representante");

                    b.HasIndex("id_proveedor");

                    b.ToTable("colaboraciones");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Deposito", b =>
                {
                    b.Property<int>("id_deposito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_deposito"));

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre_d")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id_deposito");

                    b.ToTable("depositos");
                });

            modelBuilder.Entity("ApiJBA.Entidades.DetalleColaboracion", b =>
                {
                    b.Property<int>("id_detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_detalle"));

                    b.Property<int>("cant_soli")
                        .HasColumnType("int");

                    b.Property<int>("id_deposito")
                        .HasColumnType("int");

                    b.Property<int>("id_orden")
                        .HasColumnType("int");

                    b.Property<int>("id_producto")
                        .HasColumnType("int");

                    b.HasKey("id_detalle");

                    b.HasIndex("id_deposito");

                    b.HasIndex("id_orden");

                    b.HasIndex("id_producto");

                    b.ToTable("detalle_colaboracion");
                });

            modelBuilder.Entity("ApiJBA.Entidades.DetalleRecepcion", b =>
                {
                    b.Property<int>("id_detalle_rec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_detalle_rec"));

                    b.Property<int>("cantidad_re")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fecha_vencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_producto")
                        .HasColumnType("int");

                    b.Property<int>("id_recepcion")
                        .HasColumnType("int");

                    b.HasKey("id_detalle_rec");

                    b.HasIndex("id_producto");

                    b.HasIndex("id_recepcion");

                    b.ToTable("detalle_recepcion");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Inscripcion", b =>
                {
                    b.Property<int>("id_inscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_inscripcion"));

                    b.Property<string>("ci_alumno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("fecha_inscripcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_aula")
                        .HasColumnType("int");

                    b.HasKey("id_inscripcion");

                    b.HasIndex("ci_alumno");

                    b.HasIndex("id_aula");

                    b.ToTable("inscripciones");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Matricula", b =>
                {
                    b.Property<int>("id_aula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_aula"));

                    b.Property<string>("aula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("capacidad")
                        .HasColumnType("int");

                    b.Property<string>("ci_p")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("estado_m")
                        .HasColumnType("int");

                    b.Property<int>("hembras")
                        .HasColumnType("int");

                    b.Property<string>("motivo_m")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("seccion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("turno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("varones")
                        .HasColumnType("int");

                    b.HasKey("id_aula");

                    b.HasIndex("ci_p");

                    b.ToTable("matriculas");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Operacion", b =>
                {
                    b.Property<int>("id_operacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_operacion"));

                    b.Property<string>("ci_p")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("registro_id")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tipo_operacion")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("id_operacion");

                    b.HasIndex("ci_p");

                    b.ToTable("operaciones");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Personal", b =>
                {
                    b.Property<string>("ci_p")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("correo_p")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("direccion_p")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_salida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_voucher")
                        .HasColumnType("datetime2");

                    b.Property<string>("foto_p")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("nivel")
                        .HasColumnType("int");

                    b.Property<string>("nombre_p")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tipo_preparacion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ci_p");

                    b.ToTable("personal");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Producto", b =>
                {
                    b.Property<int>("id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_producto"));

                    b.Property<int>("cant_min")
                        .HasColumnType("int");

                    b.Property<string>("codigo_corto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("id_categoria")
                        .HasColumnType("int");

                    b.HasKey("id_producto");

                    b.HasIndex("id_categoria");

                    b.ToTable("producto");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Proveedor", b =>
                {
                    b.Property<int>("id_proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_proveedor"));

                    b.Property<string>("nombre_proveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("num_proveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id_proveedor");

                    b.ToTable("proveedor");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Recepcion", b =>
                {
                    b.Property<int>("id_recepcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_recepcion"));

                    b.Property<string>("ci_p")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_orden")
                        .HasColumnType("int");

                    b.HasKey("id_recepcion");

                    b.HasIndex("ci_p");

                    b.HasIndex("id_orden")
                        .IsUnique();

                    b.ToTable("recepcion");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Representante", b =>
                {
                    b.Property<string>("ci_representante")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("carta_residencia")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ci_madre")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ci_padre")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("estado_representante")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_salida")
                        .HasColumnType("datetime2");

                    b.Property<string>("foto_madre")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("foto_padre")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("hijos")
                        .HasColumnType("int");

                    b.Property<string>("motivo_r")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nombre_madre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nombre_padre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nombre_representante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ci_representante");

                    b.ToTable("representantes");
                });

            modelBuilder.Entity("ApiJBA.Entidades.StockDeposito", b =>
                {
                    b.Property<int>("id_stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_stock"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("cantidad_min")
                        .HasColumnType("int");

                    b.Property<int>("id_deposito")
                        .HasColumnType("int");

                    b.Property<int>("id_producto")
                        .HasColumnType("int");

                    b.HasKey("id_stock");

                    b.HasIndex("id_deposito");

                    b.HasIndex("id_producto");

                    b.ToTable("stock_deposito");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Traslado", b =>
                {
                    b.Property<int>("id_tr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tr"));

                    b.Property<int>("cantidad_tr")
                        .HasColumnType("int");

                    b.Property<string>("ci_p")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("fecha_tr")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_dep_destino")
                        .HasColumnType("int");

                    b.Property<int>("id_dep_origen")
                        .HasColumnType("int");

                    b.Property<int>("id_producto")
                        .HasColumnType("int");

                    b.Property<string>("motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id_tr");

                    b.HasIndex("ci_p");

                    b.HasIndex("id_dep_destino");

                    b.HasIndex("id_dep_origen");

                    b.HasIndex("id_producto");

                    b.ToTable("traslados");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Alumno", b =>
                {
                    b.HasOne("ApiJBA.Entidades.Representante", "Representante")
                        .WithMany("Alumnos")
                        .HasForeignKey("ci_representante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Representante");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Asistencia", b =>
                {
                    b.HasOne("ApiJBA.Entidades.Personal", "Personal")
                        .WithMany("Asistencias")
                        .HasForeignKey("ci_p")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Colaboracion", b =>
                {
                    b.HasOne("ApiJBA.Entidades.Personal", "Personal")
                        .WithMany("Colaboraciones")
                        .HasForeignKey("ci_p")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiJBA.Entidades.Representante", "Representante")
                        .WithMany("Colaboraciones")
                        .HasForeignKey("ci_representante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiJBA.Entidades.Proveedor", "Proveedor")
                        .WithMany("Colaboraciones")
                        .HasForeignKey("id_proveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personal");

                    b.Navigation("Proveedor");

                    b.Navigation("Representante");
                });

            modelBuilder.Entity("ApiJBA.Entidades.DetalleColaboracion", b =>
                {
                    b.HasOne("ApiJBA.Entidades.Deposito", "Deposito")
                        .WithMany("DetalleColaboraciones")
                        .HasForeignKey("id_deposito")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiJBA.Entidades.Colaboracion", "Colaboracion")
                        .WithMany("Detalles")
                        .HasForeignKey("id_orden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiJBA.Entidades.Producto", "Producto")
                        .WithMany("DetalleColaboraciones")
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colaboracion");

                    b.Navigation("Deposito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ApiJBA.Entidades.DetalleRecepcion", b =>
                {
                    b.HasOne("ApiJBA.Entidades.Producto", "Producto")
                        .WithMany("DetalleRecepciones")
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiJBA.Entidades.Recepcion", "Recepcion")
                        .WithMany("Detalles")
                        .HasForeignKey("id_recepcion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Inscripcion", b =>
                {
                    b.HasOne("ApiJBA.Entidades.Alumno", "Alumno")
                        .WithMany("Inscripciones")
                        .HasForeignKey("ci_alumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiJBA.Entidades.Matricula", "Matricula")
                        .WithMany("Inscripciones")
                        .HasForeignKey("id_aula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Matricula", b =>
                {
                    b.HasOne("ApiJBA.Entidades.Personal", "Personal")
                        .WithMany("Matriculas")
                        .HasForeignKey("ci_p")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Operacion", b =>
                {
                    b.HasOne("ApiJBA.Entidades.Personal", "Personal")
                        .WithMany("Operaciones")
                        .HasForeignKey("ci_p")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Producto", b =>
                {
                    b.HasOne("ApiJBA.Entidades.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("id_categoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Recepcion", b =>
                {
                    b.HasOne("ApiJBA.Entidades.Personal", "Personal")
                        .WithMany("Recepciones")
                        .HasForeignKey("ci_p")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiJBA.Entidades.Colaboracion", "Colaboracion")
                        .WithOne("Recepcion")
                        .HasForeignKey("ApiJBA.Entidades.Recepcion", "id_orden")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colaboracion");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("ApiJBA.Entidades.StockDeposito", b =>
                {
                    b.HasOne("ApiJBA.Entidades.Deposito", "Deposito")
                        .WithMany("StockDepositos")
                        .HasForeignKey("id_deposito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiJBA.Entidades.Producto", "Producto")
                        .WithMany("StockDepositos")
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Traslado", b =>
                {
                    b.HasOne("ApiJBA.Entidades.Personal", "Personal")
                        .WithMany("Traslados")
                        .HasForeignKey("ci_p")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiJBA.Entidades.Deposito", "DepositoDestino")
                        .WithMany()
                        .HasForeignKey("id_dep_destino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiJBA.Entidades.Deposito", "DepositoOrigen")
                        .WithMany()
                        .HasForeignKey("id_dep_origen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiJBA.Entidades.Producto", "Producto")
                        .WithMany("Traslados")
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepositoDestino");

                    b.Navigation("DepositoOrigen");

                    b.Navigation("Personal");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Alumno", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Colaboracion", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Deposito", b =>
                {
                    b.Navigation("DetalleColaboraciones");

                    b.Navigation("StockDepositos");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Matricula", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Personal", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Colaboraciones");

                    b.Navigation("Matriculas");

                    b.Navigation("Operaciones");

                    b.Navigation("Recepciones");

                    b.Navigation("Traslados");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Producto", b =>
                {
                    b.Navigation("DetalleColaboraciones");

                    b.Navigation("DetalleRecepciones");

                    b.Navigation("StockDepositos");

                    b.Navigation("Traslados");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Proveedor", b =>
                {
                    b.Navigation("Colaboraciones");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Recepcion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Representante", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Colaboraciones");
                });
#pragma warning restore 612, 618
        }
    }
}
