// <auto-generated />
using System;
using ApiJBA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiJBA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605043930_UpdatePersonalFields")]
    partial class UpdatePersonalFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiJBA.Entidades.Operacion", b =>
                {
                    b.Property<int>("id_operacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_operacion"));

                    b.Property<string>("ci_p")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("registro_id")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tipo_operacion")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("id_operacion");

                    b.HasIndex("ci_p");

                    b.ToTable("operaciones");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Personal", b =>
                {
                    b.Property<string>("ci_p")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("correo_p")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("direccion_p")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_salida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_voucher")
                        .HasColumnType("datetime2");

                    b.Property<string>("foto_p")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("nivel")
                        .HasColumnType("int");

                    b.Property<string>("nombre_p")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tipo_preparacion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ci_p");

                    b.ToTable("personal");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Operacion", b =>
                {
                    b.HasOne("ApiJBA.Entidades.Personal", "Personal")
                        .WithMany("Operaciones")
                        .HasForeignKey("ci_p")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("ApiJBA.Entidades.Personal", b =>
                {
                    b.Navigation("Operaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
